/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FilmBioskop;

/**
 *
 * @author RIYANA
 */
import java.util.List;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import javax.persistence.*;

public class InsertDlgJadwal extends javax.swing.JDialog {

    private Utama utama;
//    private DefaultTableModel model; // simpan model dari parent
    private boolean saved = false;

    /**
     * Creates new form InsertDlgJadwal
     */
    public InsertDlgJadwal(java.awt.Frame parent, boolean modal, Utama utama) {
        super(parent, modal);
        initComponents();
        loadJadwal();
        loadStudio();
        this.utama = utama; // simpan referensi agar tidak null
    }

    public InsertDlgJadwal(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public boolean isSaved() {
        return saved;
    }

    private void loadJadwal() {
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            Query q = em.createQuery("SELECT f FROM Film f ORDER BY f.judul");
            List<Film> list = q.getResultList();

            CbJudul.removeAllItems();
            CbJudul.addItem("-- Pilih Judul Film --");

            for (Film f : list) {
                CbJudul.addItem(f.getJudul());
            }

            em.close();
            emf.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data judul: " + e.getMessage());
        }
    }

    private void loadStudio() {
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            // Ambil semua Studio, urut berdasarkan namaStudio
            Query q = em.createQuery("SELECT s FROM Studio s ORDER BY s.namaStudio");
            List<Studio> list = q.getResultList();

            CbStudio.removeAllItems();
            CbStudio.addItem("-- Pilih Studio --"); // item default

            for (Studio s : list) {
                CbStudio.addItem(s.getNamaStudio()); // tampilkan nama studio
            }

            em.close();
            emf.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data studio: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTfIdJadwal = new javax.swing.JTextField();
        jTfTanggal = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTfWaktu = new javax.swing.JTextField();
        jBtnClear = new javax.swing.JButton();
        CbJudul = new javax.swing.JComboBox<>();
        CbStudio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INPUTKAN JADWAL FILM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Id Jadwal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Judul Film");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Studio");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal Tayang");

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Waktu Tayang");

        jBtnClear.setText("Clear");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        CbJudul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CbStudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfIdJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jTfTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnClear)
                                .addGap(10, 10, 10)
                                .addComponent(jBtnSave))
                            .addComponent(CbJudul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbStudio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnClear, jBtnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTfIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CbJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CbStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSave)
                    .addComponent(jBtnClear))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnClear, jBtnSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        if (jTfIdJadwal.getText().equals("") || CbJudul.getSelectedIndex() == 0
                || CbStudio.getSelectedIndex() == 0 || jTfTanggal.getText().equals("")
                || jTfWaktu.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu!");
            return;
        }

        String idJadwal = jTfIdJadwal.getText();
        String judulTerpilih = CbJudul.getSelectedItem().toString();
        String namaStudioTerpilih = CbStudio.getSelectedItem().toString();
        String tanggalStr = jTfTanggal.getText();
        String waktuStr = jTfWaktu.getText();

        try {
            // Parsing tanggal dan waktu
            java.sql.Date tanggal = java.sql.Date.valueOf(tanggalStr); // format: yyyy-MM-dd
            java.sql.Time waktu = java.sql.Time.valueOf(waktuStr);     // format: HH:mm:ss

            // Buat koneksi persistence
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_Pertemuan12PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            // Ambil entitas Film berdasarkan judul (setiap judul unik)
            Query qFilm = em.createQuery("SELECT f FROM Film f WHERE f.judul = :judul");
            qFilm.setParameter("judul", judulTerpilih);
            Film film;
            try {
                film = (Film) qFilm.getSingleResult();
            } catch (NoResultException e) {
                JOptionPane.showMessageDialog(null, "Film tidak ditemukan di database!", "Error", JOptionPane.ERROR_MESSAGE);
                em.close();
                emf.close();
                return;
            }

            // Ambil Studio berdasarkan nama
            Query qStudio = em.createQuery("SELECT s FROM Studio s WHERE s.namaStudio = :nama");
            qStudio.setParameter("nama", namaStudioTerpilih);
            Studio studio;
            try {
                studio = (Studio) qStudio.getSingleResult();
            } catch (NoResultException e) {
                JOptionPane.showMessageDialog(null, "Studio tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                em.close();
                emf.close();
                return;
            }

            // 🔹 Validasi 1 — studio + tanggal + waktu tidak boleh sama
            Query q1 = em.createQuery(
                    "SELECT COUNT(j) FROM JadwalTayang j WHERE j.idStudio = :studio AND j.tanggalTayang = :tanggal AND j.waktuTayang = :waktu"
            );
            q1.setParameter("studio", studio.getIdStudio());
            q1.setParameter("tanggal", tanggal);
            q1.setParameter("waktu", waktu);
            long count1 = (long) q1.getSingleResult();

            if (count1 > 0) {
                JOptionPane.showMessageDialog(null,
                        "Studio ini sudah digunakan pada tanggal dan waktu tersebut!",
                        "Jadwal Bentrok", JOptionPane.WARNING_MESSAGE);
                em.close();
                emf.close();
                return;
            }

            // 🔹 Validasi 2 — film + studio + tanggal + waktu tidak boleh sama
            Query q2 = em.createQuery(
                    "SELECT COUNT(j) FROM JadwalTayang j WHERE j.idFilm = :film AND j.idStudio = :studio AND j.tanggalTayang = :tanggal AND j.waktuTayang = :waktu"
            );
            q2.setParameter("film", film);
            q2.setParameter("studio", studio.getIdStudio());
            q2.setParameter("tanggal", tanggal);
            q2.setParameter("waktu", waktu);
            long count2 = (long) q2.getSingleResult();

            if (count2 > 0) {
                JOptionPane.showMessageDialog(null,
                        "Film ini sudah dijadwalkan di studio dan waktu tersebut!",
                        "Jadwal Duplikat", JOptionPane.WARNING_MESSAGE);
                em.close();
                emf.close();
                return;
            }

            // 🔹 Validasi 3 — idJadwal tidak boleh duplikat (Primary Key)
            JadwalTayang existing = em.find(JadwalTayang.class, idJadwal);
            if (existing != null) {
                JOptionPane.showMessageDialog(null,
                        "ID Jadwal sudah digunakan! Gunakan ID lain.",
                        "Duplikat ID Jadwal", JOptionPane.WARNING_MESSAGE);
                em.close();
                emf.close();
                return;
            }

            // Buat object JadwalTayang
            JadwalTayang jadwal = new JadwalTayang();
            jadwal.setIdJadwal(idJadwal);
            jadwal.setIdFilm(film);         // relasi FK ke entitas Film
            jadwal.setIdStudio(studio.getIdStudio());
            jadwal.setTanggalTayang(tanggal);
            jadwal.setWaktuTayang(waktu);

            // Simpan ke database
            em.persist(jadwal);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Data jadwal berhasil disimpan!");

            // Bersihkan field input
            bersih();

            // Refresh tabel di JFrame (pastikan ada method showTableJadwal di JFrame)
            if (utama != null) {
                utama.showTableJadwal();
            }

            em.close();
            emf.close();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal harus yyyy-MM-dd dan waktu HH:mm:ss!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        bersih();
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void bersih() {
        jTfIdJadwal.setText("");
        CbJudul.setSelectedIndex(0);
        CbStudio.setSelectedIndex(0);
        jTfTanggal.setText("");
        jTfWaktu.setText("");
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InsertDlgJadwal dialog = new InsertDlgJadwal(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbJudul;
    private javax.swing.JComboBox<String> CbStudio;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTfIdJadwal;
    private javax.swing.JTextField jTfTanggal;
    private javax.swing.JTextField jTfWaktu;
    // End of variables declaration//GEN-END:variables
}
